### ISSUE TITLE
Issue with importing 2 streams

### ISSUE THREAD

**Issue by rschmaelzle** [sccn/xdf#20]
Hello,
I've been running into an issue repeatedly, but haven't been able to fix it. By now I've tried almost everything I could find (xdf for matlab, sigviewer, python, the reader in lsl, eeglab, various versions of xdf, and suggestions in lsl, eeglab, git issues), so this is my last resort: I am trying to load an XDF file that has 2 eeg datastreams in it. I can load the first, but not the second one. 
Here is the [Xdffile](https://drive.google.com/open?id=1i1ZhvjHms7tR8pnz76st2dYPNDOzpEDY) 
 and this is my code (on eeglab using the plugin, with Matlab2016b and eeglab13.6.5
```
 EEG = pop_loadxdf('/Users/Ralf/Desktop/2sigsTest2.xdf' , 'streamname', 'EEG115'); EEG.setname='t';
Now importing...done.
EEG checkset note for expert users: Noze direction now set to default +X in EEG.chanlocs and EEG.dipfit.
>> EEG = pop_loadxdf('/Users/Ralf/Desktop/2sigsTest2.xdf' , 'streamname', 'EEG114'); EEG.setname='t';
Now importing...Reference to non-existent field 'effective_srate'.

Error in eeg_load_xdf (line 66)
if args.effective_rate && isfinite(stream.info.effective_srate) && stream.info.effective_srate>0

```
I've also tried to load the stream with python, and can also access the data for the first one, but not for the second. I also tried to change the code or the file to overcome the effective_srate issue, but didn't succeed. I admit my understanding of the xdf format and the loading functions is limited, but I get the gist. The issue is that I don't fully understand if it  might be an system issue (working on Mac), the functions have a bug, or the format/file might not be correct. Any help is appreciated.

Best, Ralf.

**Comment by dmedine** [comment]
I loaded it into Matlab without error using load_xdf and saw the same 
thing as Chadwick, i.e. an empty stream for EEG114.

The error is thrown by EEGLab. This has nothing to do with xdf or LSL 
per se. Your EEG114 stream has no effective sampling rate because that 
is just the inverse of the average time between the post-processed data 
points' timestamps. Your stream has no data whatsoever, so no such value 
can be calculated and subsequently the data structure holding all the 
information about the stream doesn't have this field.

What might be an LSL issue is the fact that one of your streams is 
empty. This could be a problem with the device itself, the LSL 
implementation by mbraintrain (which I doubt because I've never 
encountered an issue like this from a smarting device before, but one 
never knows), or a network configuration issue. Try recording one stream 
at a time and see if that helps you to isolate the issue.

You should also be aware of XDFBrowser 
(ftp://sccn.ucsd.edu/pub/software/LSL/Apps/XDFBrowser-1.10.zip) which is 
a utility to help peer inside of an xdf file.

**Comment by rschmaelzle** [comment]
Hi dmedine and cboulay.
thanks so much for the reply. both helped me a lot and I've lookked more into xdfbrowser and it is good to know that pyxdf is under active development. My issue has been tentatively resolved (the file recording did not record the stream, so the missing data is "normal") and your comments helped spot the reason. Thanks and best, r
