### ISSUE TITLE
Motion capture metadata (Orientation ABCD)

### ISSUE THREAD

**Issue by sjeung** [sccn/xdf#57]
How are the quaternion orientation channels to be interpreted in motion capture metadata?
The xdf wiki page specifies A,B,C, and D as names for quaternion elements.
How do they correspond to the X,Y,Z axes and real/imaginary elements of quaternions? I had difficulty figuring out the correct quat to eul conversion from the documentation and while it is possible to try out different configurations to visually see the correct mapping to the spatial axes, this seems to be left flexible.
Pitch, roll, and heading also makes a lot of intuitive sense but I am failing to read the order of rotations applied. Would it make sense to follow a style that is specified in for instance this proposal for extending Brain Imaging Data Structure for [motion data](https://docs.google.com/document/d/1iaaLKgWjK5pcISD1MVxHKexB3PZWfE2aAC5HF_pCZWo/edit#heading=h.4k1noo90gelw)? If there is anything I can contribute regarding this I would be more than happy to.

**Comment by chkothe** [comment]
For the quaternions, the (A,B,C,D) are the 4 components of the quaternion,  following the [wikipedia](https://en.wikipedia.org/w/index.php?title=Quaternion&oldid=1019295354) or [MathWorld](https://mathworld.wolfram.com/Quaternion.html) nomenclature. Game engines (Unity, Unreal) seem to often use X,Y,Z,W but when you look closely, you see that they order them as W, X, Y, Z in some of their docs (so the 3 axial components come last, and those happen to also correspond to the last three B, C, D components). However, I wouldn't be surprised if there was some MoCap system that wrote X,Y,Z,W instead of W,X,Y,Z into A,B,C,D channels. Note that there's also an alternative format in which orientations can be declared for systems that emit those, using Pitch, Heading, and Roll (PHR), but few if any system seem to use those (not surprising given gimbal lock issues etc). It's not explicitly stated in which order they'd be applied, but anything other than in the written order would be quite surprising. In theory one could also add an axis-angle format using OrientationX, OrientationY, OrientationZ, OrientationW for systems that support that (it'd be more visually intuitive but then again, most 3d software tools can already take in quaternions, and the existing LSL applications and recordings aren't going away, so then we'd be at 3 different formats to support).

**Comment by sjeung** [comment]
Thanks again for the reply. As you have pointed out the XZYW to ABCD mapping can be arbitrary. I have even seen a data set where C was the w component and I am not sure if this was intentional. It was recognizable from the odd output from conversion to Euler angles. Is there an advantage of choosing ABCD over xyzw? When quaternions are associated with rotations, qw qx qy qz or xyzw style of notations are often seen (like on this [wiki page](https://en.wikipedia.org/wiki/Conversion_between_quaternions_and_Euler_angles)) and I personally find this much informative. 
Regarding Euler angles representation, I think the relevance depends on whether .xdf focuses on computer generated orientation streams or also deals with output from gyroscopes, which would be angular velocity around different axes. Depending on which object it is tracking, the terms pitch, roll, and heading may not mean as much as rotation around X, Y, or Z axes. I can't really guess how problematic this can be, (that one would not be able to map the rotation axes to position axes for objects that have no obvious PHR, like, a mug...) but it is also true that PHR probably applies to a majority of use cases.

**Comment by cboulay** [comment]
I'm surprised that BIDS is leaning toward mandating Euler angles. Euler angles are more intuitive for interaction but they are degenerate. Pretty much all 3D software uses quats under the hood even if they give you tools to manipulate things in Euler angles. (Aside: I encounter YPR more often than PHR). I wouldn't recommend LSL/XDF users store data as only Euler angles because you can lose information and it can be unrecoverable. Of course if the data source provides only Euler angles then there's no point in transforming it to quaternions just for storage.

For my OpenVR app, I took a slightly different approach and represented the controller pose with a 3x4 transformation matrix: https://github.com/labstreaminglayer/App-OpenVR/blob/master/src/openvrthread.cpp#L223-L226
This stores position and orientation, and there's no ambiguity there! But it does take 12 channels to store what could be equally represented in 7, so it's pretty inefficient.

I think that as long as developers encode what each channel means in the stream metadata then it's really not up to LSL or XDF to mandate that a certain data modality must be stored in a specific way. This comparison might be a bit of a stretch, but we wouldn't say that all EEG caps have to have the exact same 32 channels in the exact same order. To me this is the same thing. If someone doesn't name their EEG channels properly then the data are uninterpretable. If someone doesn't name their orientation channels properly then the data are uninterpretable.

I generally take the approach of trying to match what the manufacturer provides as closely as possible. If they give x,y,z,w then I'd use that. If they give a,b,c,d then I'd use that. Usually manufacturers have their own reason for choosing a certain format. If the joint fields of architecture, 3D gaming, and motion capture for art or biomedical science haven't agreed on a standard for how to store quats then I don't think LSL is going to be the one to solve it.

**Comment by chkothe** [comment]
Thanks for the input, we will definitely make an amendment noting that the B,C,D correspond to the axial components in case it was unclear. Fortunately it seems like at least the math departments are in reasonable agreement about what is what in those coefficients and the 2 most accessible sources (wikipedia and wolfram) agree in all the details, so that helps. I suspect the discrepancy in lettering comes from math textbooks (a,b,c,d like in, e.g, a plane equation) vs. engine developers (x,y,z,w like in axis-angle rotators or homogeneous coordinates). One reason we're not calling them XYZW in XDF is that then you wouldn't know from the labels if it's an axis-angle rotator or a quaternion.

Btw I'm curious where you found C being W - was this in an LSL application or XDF recording? If so we'd probably inform the vendor that something may be amiss there.

**Comment by sjeung** [comment]
@cboulay of course, XDF should support quaternions for reasons you have mentioned. BIDS orientation representation was chosen following a [community survey](https://github.com/JuliusWelzel/BIDS-BEP029/blob/master/pub_srvy_res/report_results_survey.md) and quaternions came in the second place following Euler angles (16 for Euler and 10 for quaternions).  It can be that the survey did not gain enough visibility to people who work only with virtual motion. The specification is still subject to change and we decided to first start from somewhere. I believe there are some differences between what XDF as data format aims at (precision, prevention of data loss) and what BIDS tries to achieve. To my understanding BIDS prioritizes making it easy for people to comprehend and analyze the data recorded alongside neuroimaging data. In typical studies using mocap or virtual recordings of motion, Euler angles are seen as a useful representation, but not in every context. If people want to use that data for developing games, operating robots or making an animation, I agree that quaternions would be better suited. 

Also reading your reply, I might have misunderstood the implication of the comments on [sccn xdf wiki page on MoCap metadata] (https://github.com/sccn/xdf/wiki/MoCap-Meta-Data). If these comments are not restrictions on keywords, then the metadata would need to be documented elsewhere, maybe even outside of the .xdf file. But it would make things super easy for writing scripts that converts .xdf data sets to BIDS to simply be able to assume certain naming convention, without being restrictive of the representation itself.

**Comment by sjeung** [comment]
@chkothe I understand. And thanks for looking further into this. With axis correspondence established, it will be already much easier to operate on quaternion data in .xdf. The C being w was found in a data set that uses a marker-based mocap system collected by someone else in my group. I am unfortunately not aware of which LSL app was used but I will certainly ask and send feedback if this wasn't some glitch specific to this project.

**Comment by chkothe** [comment]
Great, thanks!
