### ISSUE TITLE
Stream Times Are Not Synchronized

### ISSUE THREAD

**Issue by krigolson** [sccn/xdf#59]
Hi, I have loaded some EEG data that has event markers in it - and the time stamps appear to be not synchronized so when I load the data into EEGLAB the marker latencies are all the same and 1. I am using the latest version of all the software and note sure what is going wrong here. HELP!

**Comment by cboulay** [comment]
I assume the XDF file was saved with LabRecorder?
What were the stream sources?

**Comment by krigolson** [comment]
Hi,

Yes, it was indeed. The first stream was EEG data from a Muse Headband and
the second stream was from MATLAB as a marker stream. We have had success
in the past so we are not sure what has changed except we are supporting
this project remotely. Both streams appeared in Lab Recorder and both are
in the .xdf file.

The only quirk I noticed was it said that the sampling rate of the marker
stream was 0 so it threw a warning on import.

Thank you for the response!


Olav Krigolson, PhD

[signature snipped by Chad to help protect you from spam bots]

**Comment by dmedine** [comment]
`load_xdf.m` should be never issue a warning when the sampling rate is 0. This was added some time back and it is wrong. It is completely anathema to how LSL represents Marker streams, which by their very definition have a sampling rate of 0. All marker streams should have a sampling rate of 0 and they should never spawn this warning when loaded. I will submit a PR to address this, but rest assured, this has nothing to do with your issue. 

Can you please make available your problematic data file so that I can look at it? From your description it is difficult to understand what is happening.

Also, I realize that it came into the post because you most likely replied via email and it is in your signature, but please try to avoid advertising on this forum. It is not appropriate. You should probably also avoid posting personal information such as your telephone number and mailing address. Anyone can see this. Just a friendly word of warning.

Finally, since this has to do with EEGLAB, I am going to close this issue and reopen it on the xdf matlab submodule issues: https://github.com/xdf-modules/xdf-Matlab/issues/13

**Comment by dmedine** [comment]
Actually, I think I already fixed this 0 sampling rate warning some time back, although I couldn't track down the commit in the matlab module or the xdf module. In any case, the current source code in both modules does not issue this warning. I would guess that you are using an older version of EEGLAB.

**Comment by krigolson** [comment]
Here is the sample datafile.
