### ISSUE TITLE
Mandatory XML content

### ISSUE THREAD

**Issue by Garfield100** [sccn/xdf#64]
Hello again,

In the [StreamHeader chunk section](https://github.com/sccn/xdf/wiki/Specifications#streamheader-chunk) of the specification, the given XML example is described as "[...] the minimal XML content as populated by an early client [...]". It contains quite a few tags.
In contrast, the streams in the `minimal.xdf` example file have fewer tags.

The following tags are shared between the two sources:
```
name
type
channel_count
nominal_srate
channel_format
created_at
uid
```
These additional tags, not found in minimal.xdf, are included in the spec example:
```
source id
version
session_id
hostname
```
`minimal.xdf` also has the `desc` tag, which is not in the spec. Although it is empty, it _is_ there.

The situation is similar with the StreamFooter XML with tags like `writer`, `clock_offsets`, and `measured_srate`.

So I ask: which tags are truly mandatory for an XDF file and which are optional?
And why are clock offsets included again in the footer when they already have their own chunks?

**Comment by chkothe** [comment]
Hi Enrico, the XDF spec follows the usual convention of using the "must" and "should" keywords to indicate what's mandatory vs advised but not required, and therefore only the fields where the spec says they _must_ be present, are formally mandatory (those are `channel_count`, `nominal_srate`, and `channel_format`), since those are the fields needed to decode the binary time-series payload. As such, the mandatory core subset of XDF is a bare multi-stream time-series container where all content meta-data is optional.

However, there are a 3 additional fields where the spec says they _should_ be present for actual interpretability of the data, which are `name`, `type`, and `desc` (btw note that `desc` is actually both in the spec text and in the example snippet), and much of the practical value of XDF comes from the content of those fields. For that reason, applications that load XDF files will probably complain or error out if those three fields are not present, since most applications do something that depends on the content type ("modality") of the stream. This is enabled by additional modality-specific appendix [pages](https://github.com/sccn/xdf/wiki/Meta-Data#stream-content-types) of the spec that describe pre-defined values for `type` (the stream content-type), and pre-defined sub-fields for `desc` according to that content-type. XDF is open-ended / extensible with regards to the kinds of data modalities that may be stored in it, and most practical applications will only write or interpret the subset of `desc` that is relevant to the application's domain -- for example, typical EEG software will not interpret (and will therefore ignore) a stream containing video data and vice versa. Only very few programs (multi-modal data analysis software) would interpret the majority of XDF fields.

The minimal.xdf example file is mainly for the convenience of those who want to test their importers and was created using a real-world client (I believe) after a few years of XDF having been out "in the wild", which is likely why a few (technically non-mandatory) fields like `created_at` and `uid` were not stripped out of the file, even though that renders the file not strictly minimal (that said, generally, XDF files may contain any number of additional fields, for forward compatibility, and importers are not supposed to choke on those, so that's why this file is still a useful test case, even though it is not the single source of truth about what's mandatory or not).

Let's talk about the StreamFooter chunk. That chunk is there for two purposes: a) to indicate that the file was completed/transmitted in full and not somehow truncated (e.g. when a recording crashed), and b) as a reserved area where current applications, or future revisions of the XDF spec, may store additional information that enables faster loading of, or seeking into, the data (because it would be costly to traverse the whole file to collect certain summary information). At this time the spec does not consider anything there mandatory, because the initial version of the spec is intentionally lean to help adoption, and if you are writing an application that generates XDF files, you should be able to safely write an empty chunk there (if an importer chokes on an empty StreamFooter chunk, that's probably a bug and worth fixing*). The second reason why the spec has no mandatory fields in this chunk is that XDF content is intended to be fully interpretable even if the file was truncated at the end (if your recording crashes after 3h, you should have 3h worth of usable data).

Hope that helps! And let me know if you have additional questions.

*: of course the developers of those importers are free to disagree with me here.

**Comment by Garfield100** [comment]
In retrospect "must" vs "should" _should_ have been more obvious to me 😅
Thank you for your swift answer, I have no further questions.

**Comment by chkothe** [comment]
No problem! It's still a fair question, because many XDF files probably contain most or all fields in the `<info>` example in the spec, and some applications might try to eagerly read some or all of those and fail of one is not present (that's again a thing that should be fixed in the application's importer). That said, we've been maintaining a piece of software (NeuroPype) that definitely doesn't write anything other than those 6 fields, and we haven't yet had a problem with any XDF files created by that in now 8 years. On the footer chunk I should say that, if the footer chunk is present, then the `<info>` tag may be expected to be there (even if empty) by applications that look at the footer, just because of the way those applications tend to be written. That's one thing that I think could be clarified in the spec, but OTOH we'd also be hesitant to make it stricter on a whim and invalidate some existing and otherwise perfectly compliant files.
