### ISSUE TITLE
Deducing timestamps

### ISSUE THREAD

**Issue by Garfield100** [sccn/xdf#65]
Hello again :)

I've been testing my reader with `minimal.xdf` and got confused by some failing tests.
To be more specific, my reader extracted all the values of the first stream but, according to minimal.md, missed some of the timestamps.
minimal.md specifies the following for the 9 samples in the first stream: "Timestamps: 5.1 to 5.9 in .1 steps"
My code only found a few of those. Confused, I employ the python implementation to compare which (after rounding to one decimal) yielded the following:
```
(5.0, array([192, 255, 238], dtype=int16)),
 (5.1, array([12, 22, 32], dtype=int16)),
 (5.2, array([13, 23, 33], dtype=int16)),
 (5.3, array([14, 24, 34], dtype=int16)),
 (5.4, array([15, 25, 35], dtype=int16)),
 (5.5, array([12, 22, 32], dtype=int16)),
 (5.6, array([13, 23, 33], dtype=int16)),
 (5.7, array([14, 24, 34], dtype=int16)),
 (5.8, array([15, 25, 35], dtype=int16))
 ```
Strangely these timestamps appear to be off by 0.1 but at least each sample has one, unlike my implementation.
Since the docs, my implementation, and pyxdf yield 3 different results, I looked to the C++ implementation and got the following:
```
5 [192 255 238] 
5.1 [12 22 32] 
5.2 [13 23 33] 
5.3 [14 24 34] 
5.4 [15 25 35] 
5.5 [12 22 32] 
5.6 [13 23 33] 
5.7 [14 24 34] 
5.8 [15 25 35]
```
Same as python, so I guess at least one result seems to win, right?
Welp, I decided to manually inspect the raw chunks bytes my implementation spit out and annotate the bytes:
<details>
<summary>pain</summary>

```
//the first sample chunk
[
    0, 0, 0, 0,                             //streamID
    4,                                      //numSamples bytes
    1, 0, 0, 0,                             //numSamples

    //first sample (1)
    8,                                      //numTimestampBytes
    102, 102, 102, 102, 102, 102, 20, 64,   //timestamp = 5.1
    192, 0,                                 //val 1
    255, 0,                                 //val 2
    238, 0                                  //val 3
]

//the second sample chunk
[
    0, 0, 0, 0,                             //streamID
    4,                                      //numSamples bytes
    4, 0, 0, 0,                             //numSamples

    //first sample (2)
    8,                                      //numTimestampBytes
    205, 204, 204, 204, 204, 204, 20, 64,   //timestamp = 5.2
    12, 0,
    22, 0,
    32, 0,

    //second sample (3)
    0,                                      //numTimestampBytes = no timestamp
    13, 0,
    23, 0,
    33, 0,
    
    //third sample (4)
    0,                                      //numTimestampBytes = no timestamp
    14, 0,
    24, 0,
    34, 0,

    //fourth sample (5)
    8,                                      //numTimestampBytes
    0, 0, 0, 0, 0, 0, 22, 64,               //timestamp = ????
    15, 0,
    25, 0,
    35, 0
]

//the third sample chunk
[
    0, 0, 0, 0,                             //stream ID
    4,                                      //numSamples bytes
    4, 0, 0, 0,                             //numSamples

    //first sample (6)
    8,                                      //numTimestampBytes
    102, 102, 102, 102, 102, 102, 22, 64,   //timestamp = 5.6
    12, 0,
    22, 0,
    32, 0,
    
    //second sample (7)
    0,                                      //numTimestampBytes = no timestamp
    13, 0,
    23, 0,
    33, 0,
    
    //third sample (8)
    0,                                      //numTimestampBytes = no timestamp
    14, 0,
    24, 0,
    34, 0,
    
    //fourth sample (9)
    0,                                      //numTimestampBytes = no timestamp
    15, 0,
    25, 0,
    35, 0
]
```

</details>

Admittedly these bytes ran through my program but I trust I at least got the chunk splitting part right as that never seems to misalign and the numbers all seem to fit the expected structure (zeroes or eights at certain spots, sample values matching docs etc).
After this my confusion grew even further. Clearly there are no timestamps for some of these samples, so how did pyxdf and libxdf still display some? After realising I should have done this way earlier I took a quick look at pyxdf which revealed the [following](https://github.com/xdf-modules/pyxdf/blob/5384490b96c96d0a2371541f4b50ee90e8c47b6f/pyxdf/pyxdf.py#L458):
```py
# read or deduce time stamp
if f.read(1) != b"\x00":
    stamps[k] = struct.unpack("<d", f.read(8))[0]
else:
    stamps[k] = s.last_timestamp + s.tdiff
```
If there is no timestamp, it is calculated using the last one and the nominal_srate.

So my questions are these:
* Is this expected? I'm forgetful and tired but I couldn't find anything in the specification.
* Is it "5.1 to 5.9 in .1 steps" as specified in minimal.md right or are pyxdf and libxdf correct with the 5.0 to 5.8?

**Comment by chkothe** [comment]
Hey, yes this is indeed expected -- if a sample in a chunk does not have a time stamp, then, if the stream has a regular sampling rate (nominal_rate != 0), the time stamp of that sample would be inferred to be the previous sample's time stamp plus the sample interval (1/nominal_rate). That's a type of delta compression for the time stamps (with known delta), and the reason that's used is that in high-rate / low-channel streams (eg audio), the time stamps would otherwise use up a large amount of storage space (potentially more than the data itself), and the other reason is that for time-series data that was acquired in chunks (most such data), the only thing that needs a measured time stamp is basically the first sample in each chunk. Not your fault there since the spec doesn't actually explain how to deduce missing stamps (that's currently left as an exercise for the reader).

**Comment by Garfield100** [comment]
Thanks! I take less issue with the spec not explaining *how* to do it and more that it doesn't directly say this compression is a feature at all. It makes a lot of sense though.

I know this is a much more time consuming question to answer but do pyxdf and libxdf's outputs mean the minimal.md doc is wrong?

**Comment by chkothe** [comment]
Agreed, that should be noted (and I'll do that).

Re which is correct: I just looked at `minimal.xdf` myself, and indeed the _raw_ time stamps for both streams in the file are 5.1 to 5.9. However, here's where the discrepancy comes from: one of the two streams, the one labeled "SendDataC", has 2 clock offset chunks, and the offset stored in both is -0.1, and both libraries by default apply that correction to that stream, which is why they output 5.0 to 5.8 for that stream (you can disable that flag upon load and then you get the 5.1 to 5.9 for both streams). Now the part that _is_ inconsistent about the file is that the stream footer has entirely different clock offset readings in it (which it shouldn't, since those are meant to be a redundant summary), and I think that's because the file was at least partially handcrafted, perhaps to test the clock offset math (that would be a q for Tristan), so I think that should definitely be noted in the readme in any case, but it'd be preferable if that file was internally consistent. Now the two libraries don't actually use the offset values noted in the footer, but the (normally identical) ones in the actual clock offset chunks, which is because they'd need to use those chunks anyway if the footer was truncated off and there's no point in having two code paths during import.

**Comment by Garfield100** [comment]
Ah that makes sense, while reviewing manually I only read the footer and didn't think to compare it to the actual clock offset chunks. As such I didn't think it would make a difference that I hadn't yet implemented clock offsets. Thanks again for your continued help.
